// Trust root for module signing.
//
// CRITICAL: the keys below are PLACEHOLDERS. A real classified deployment
// MUST replace them with hardware-anchored keys whose private halves live
// in an HSM controlled by the laboratory ISSO. Shipping with the dev key
// in the trust root makes any signature meaningless. The deploy gate in
// §8.7 of FORK.md exists for this reason.
//
// Each entry binds a base64 SPKI Ed25519 public key to a list of clearance
// levels the signer is approved to attest to. A signer approved for "secret"
// cannot validly sign a manifest that claims "q-cleared", and the verifier
// rejects such a mismatch even if the signature itself is mathematically
// valid.

import type { ClearanceLevel } from "./module-manifest.js";

export type TrustedSigner = Readonly<{
  keyId: string;
  publicKeyPem: string;
  approvedClearance: ReadonlyArray<ClearanceLevel>;
  description: string;
  notAfter?: string;  // ISO date; verifier rejects manifests after this
}>;

// The default trust root ships only with the OpenClaw publisher key,
// approved for unclassified + cui modules. This keeps the open flavor
// usable out-of-the-box for community modules without claiming any
// classified attestation. A lab MUST overwrite or augment this list with
// their own internal Q-cleared signing keys before turning on the
// enclaved flavor.

const PLACEHOLDER_ENCLAWED_PUBKEY = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAGb9ECWmEzf6FQbrBZ9w7lshQhqowtrbLDFw4rXAxZv8=
-----END PUBLIC KEY-----
`;

// Reference highest-tier signer for the bundled mcp-attested module.
// Generated by scripts/dev/sign-module-manifest.mjs during module dev. The
// private half was discarded after signing the reference manifest; the
// deploying organization will replace this entry with a signer whose
// private key lives in an HSM (PKCS#11) or equivalent hardware key store.
const REFERENCE_ATTESTED_PUBKEY = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAzSWxiIufG9qsDIvBjEIDSIhbLNLHB0UGP9+eQmKIFzc=
-----END PUBLIC KEY-----
`;

// Bundled-extension dev signer. scripts/dev/sign-all-bundled-manifests.mjs
// uses this key to sign every shipped extensions/<id>/enclawed.module.json.
// The private half was discarded immediately after signing — re-run the
// script to regenerate; the public half here must then be updated to
// match scripts/dev/bundled-signer.json. A real classified deployment
// replaces this entry (and re-signs every manifest) with an HSM-anchored
// signer.
const BUNDLED_DEV_PUBKEY = `-----BEGIN PUBLIC KEY-----
MCowBQYDK2VwAyEAe7loUN6tIE+wnJ1RfrDLKMK6SfXRojneuJI++ysLnfA=
-----END PUBLIC KEY-----
`;

export const DEFAULT_TRUST_ROOT: ReadonlyArray<TrustedSigner> = Object.freeze([
  Object.freeze({
    keyId: "openclaw-community-2026",
    publicKeyPem: PLACEHOLDER_ENCLAWED_PUBKEY,
    approvedClearance: Object.freeze(["public", "internal"] as ClearanceLevel[]),
    description:
      "Placeholder community signer. Replace before any high-trust deployment.",
  }),
  Object.freeze({
    keyId: "enclawed-bundled-dev-2026",
    publicKeyPem: BUNDLED_DEV_PUBKEY,
    approvedClearance: Object.freeze(["public", "internal"] as ClearanceLevel[]),
    description:
      "Bundled-extension dev signer. Signs every shipped extensions/<id>/enclawed.module.json. " +
      "Replace with an HSM-anchored signer before any non-dev deployment.",
  }),
  Object.freeze({
    keyId: "enclawed-attested-reference-2026",
    publicKeyPem: REFERENCE_ATTESTED_PUBKEY,
    approvedClearance: Object.freeze([
      "public",
      "internal",
      "confidential",
      "restricted",
      "restricted-plus",
    ] as ClearanceLevel[]),
    description:
      "Reference highest-tier signer for the bundled mcp-attested module. " +
      "Replace before production; private key was destroyed after manifest signing.",
  }),
]);

let runtimeTrustRoot: ReadonlyArray<TrustedSigner> = DEFAULT_TRUST_ROOT;
let trustRootLocked = false;

export class TrustRootLockedError extends Error {
  override name = "TrustRootLockedError";
  constructor() {
    super("trust root is locked; setTrustRoot/resetTrustRoot rejected post-lock");
  }
}

export function getTrustRoot(): ReadonlyArray<TrustedSigner> {
  return runtimeTrustRoot;
}

// Replace the trust root at boot time. Call this from a deploying-org
// bootstrap shim that loads trusted signers from a HW-anchored config
// (e.g. files on a verified-boot partition, PKCS#11 reads from an HSM).
// Refuses if the trust root has been locked.
export function setTrustRoot(signers: ReadonlyArray<TrustedSigner>): void {
  if (trustRootLocked) throw new TrustRootLockedError();
  if (!Array.isArray(signers)) {
    throw new TypeError("setTrustRoot: signers must be an array");
  }
  for (const s of signers) {
    if (!s || typeof s.keyId !== "string" || !s.publicKeyPem || !s.approvedClearance) {
      throw new TypeError("setTrustRoot: each signer must define keyId, publicKeyPem, approvedClearance");
    }
  }
  runtimeTrustRoot = Object.freeze(signers.map((s) => Object.freeze({ ...s })));
}

export function findSigner(keyId: string): TrustedSigner | undefined {
  return runtimeTrustRoot.find((s) => s.keyId === keyId);
}

// Lock the trust root so no further mutations succeed. Bootstrap calls this
// in the enclaved flavor immediately after the deploying organization's
// signers are loaded; from that point on, no module code can substitute a
// different trust root inside the running process.
export function lockTrustRoot(): void { trustRootLocked = true; }

export function isTrustRootLocked(): boolean { return trustRootLocked; }
