export const browserCoreExamples = [
  "enclawed browser status",
  "enclawed browser start",
  "enclawed browser start --headless",
  "enclawed browser stop",
  "enclawed browser tabs",
  "enclawed browser open https://example.com",
  "enclawed browser focus abcd1234",
  "enclawed browser close abcd1234",
  "enclawed browser screenshot",
  "enclawed browser screenshot --full-page",
  "enclawed browser screenshot --ref 12",
  "enclawed browser snapshot",
  "enclawed browser snapshot --format aria --limit 200",
  "enclawed browser snapshot --efficient",
  "enclawed browser snapshot --labels",
];

export const browserActionExamples = [
  "enclawed browser navigate https://example.com",
  "enclawed browser resize 1280 720",
  "enclawed browser click 12 --double",
  "enclawed browser click-coords 120 340",
  'enclawed browser type 23 "hello" --submit',
  "enclawed browser press Enter",
  "enclawed browser hover 44",
  "enclawed browser drag 10 11",
  "enclawed browser select 9 OptionA OptionB",
  "enclawed browser upload /tmp/enclawed/uploads/file.pdf",
  'enclawed browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "enclawed browser dialog --accept",
  'enclawed browser wait --text "Done"',
  "enclawed browser evaluate --fn '(el) => el.textContent' --ref 7",
  "enclawed browser console --level error",
  "enclawed browser pdf",
];
